### ISSUE TITLE
Problem with page demo/format-custom.md

### ISSUE THREAD

**Issue by ShasonB** [tinymce/tinymce-docs#1105]
The custom format doesn't even show up when editing on code pen. It only shows the default formats in the codepen view.
> *affected page: https://www.tiny.cloud/docs-4x/demo/format-custom/*

**Comment by tylerkelly13** [comment]
Hi @ShasonB.
I've been unsuccessful in reproducing this issue in Chrome and Firefox. 
The Custom formats appear on the second toolbar as intended and the relevant code is shown in the JS editor starting at line 9. 
The issue may have been resolved since you filed this issue.
![Screenshot 2019-07-17 10:45:07](https://user-images.githubusercontent.com/14833627/61339213-139f5480-a880-11e9-80b3-506d989253e9.png)
Please reopen or create a new issue if this issue should not have been closed.
