### ISSUE TITLE
Missing documentation on removed methods from windowmanager on page migration-from-4x.md

### ISSUE THREAD

**Issue by Stetzon** [tinymce/tinymce-docs#1173]
Document removed methods on the `tinymce.windowmanager` object.

v4: https://www.tiny.cloud/docs-4x/api/tinymce/tinymce.windowmanager/#methods

- getParams()
- setParams()
- getWindows()

removed from v5: https://www.tiny.cloud/docs/api/tinymce/tinymce.windowmanager/#methods

is there a replacement for these methods?

> *affected page: https://www.tiny.cloud/docs/migration-from-4x/*

**Comment by EkimChau** [comment]
Hi Stetzon,

TinyMCE 5's dialogs work quite differently from 4.x.

When a dialog is created, it returns a dialog Instance api which you can use to set or getParams.
See https://www.tiny.cloud/docs/ui-components/dialog/#dialoginstanceapi

Updating TinyMCE 4 dialogs to TinyMCE 5, will require some logic changes as TinyMCE 5's data model will track changes to any form values so that when submit is pressed, the dialog api will return all the form data in a simple json structure which you can define.  

For example to get the Param from input1, input2, checkbox1, just call the api
var data = api.getData();
console.log(data.input1, data.input2, data.checkbox1)

Similarly you can also setData({ ..new data.. })

hope that helps

Ekim

**Comment by tylerkelly13** [comment]
Hi @Stetzon, 

We have updated the Migration from TinyMCE 4 guide to include changes to `tinymce.windowManager`: https://www.tiny.cloud/docs/migration-from-4x/#customdialogs

Please reopen or create a new issue if this issue should not have been closed.
