### ISSUE TITLE
How to load local tinymce.min.js using @tinymce/tinymce-react

### ISSUE THREAD

**Issue by zacksysbox** [tinymce/tinymce-docs#1201]
I wish to opt out Tinymce Cloud
> *affected page: https://www.tiny.cloud/docs/integrations/react/*

**Comment by tylerkelly13** [comment]
To learn how-to use TinyMCE self-hosted with React, see: https://www.tiny.cloud/docs/integrations/react/#loadingtinymcebyyourself and https://www.tiny.cloud/docs/advanced/usage-with-module-loaders/. We are currently updating this page to provide better information for developers who want to 'self-host' TinyMCE rather than the Tiny Cloud.
