### ISSUE TITLE
editor.ui.registry.addButton() since version 5.1

### ISSUE THREAD

**Issue by migliori** [tinymce/tinymce-docs#1366]
Hi,

Until now I was calling editor.ui.registry.addButton() from editor.on('init') callback in my [Tinymce Bootstrap plugin](https://www.tinymce-bootstrap-plugin.com)

The V5.1 broke this, now editor.ui.registry.addButton() MUST be called on Setup

Maybe this could be mentioned in the documentation changelog?

**Comment by lnewson** [comment]
Hi @migliori, this wasn't something intentional, as it should really never have worked when adding buttons on `init`. This is because the buttons need to be added before the UI is rendered, which happens before the `init` event is fired. Additionally, all of our documentation examples show it should be done in `setup` instead of on `init`, so we don't believe this needs to be mentioned.

**Comment by migliori** [comment]
Thank you for your answer; indeed it makes sense to build the UI before initializing
