### ISSUE TITLE
I can't find what I'm looking for: plugins/mediaembed.md

### ISSUE THREAD

**Issue by JimLudden** [tinymce/tinymce-docs#1467]
Need end-user (editor) instructions.  There appear to be three modes to insert Media and I need to know the differences and how to use each mode.
![TinyMCE Insert Media window](https://user-images.githubusercontent.com/64796100/80985191-1c9beb00-8dec-11ea-82f8-9fec272f8225.png)

**Comment by tylerkelly13** [comment]
Hi @JimLudden,

Due to the flexibility of the editor, we do not provide end-user documentation at this time.

The general tab is basic image options provided by the `media` plugin. The source field accepts a URL, such as: https://www.youtube.com/watch?v=o87KGWPFcrk.

The Embed tab accepts HTML elements for embedding media, such as: ```
<iframe width="560" height="315" src="https://www.youtube.com/embed/o87KGWPFcrk" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
```

The Advanced tab has the following fields:
"Alternative source URL" - Allows the user to specify alternative sources for the media, such as an alternative video format.
"Media poster (Image URL)" - Allows the user to set the 'poster' image for the embed media, rather than relying on the 'poster' image given by the media provider.

Hope this helps,
Tyler

**Comment by JimLudden** [comment]
Tyler,

Thanks.  It appears that ‘Advanced’ is what I need.  I appreciate your filling in. What you provided will help me get our website where we want it.

**Comment by tylerkelly13** [comment]
No problem @JimLudden. Happy to help.
