### ISSUE TITLE
I can't find what I'm looking for: api/tinymce.editor.ui/tinymce.editor.ui.registry.html

### ISSUE THREAD

**Issue by ShivSoni5** [tinymce/tinymce-docs#1583]
I am trying to add an icon into my TinyMCE and use it for a button. But instead of getting the icon, I'm getting a bomb image.

How I created icon in **Setup** - 
`editor.ui.registry.addIcon('myIcon', 'M27,7.216,24.784,5,16,13.784,7.216,5,5,7.216,13.784,16,5,24.784,7.216,27,16,18.216,24.784,27,27,24.784,18.216,16Z');
`

Then in button creation, I used it like - 
`editor.ui.registry.addButton('InsertPipe', {
        icon: 'myIcon',
        tooltip: 'Icon test',
        onAction: (_) => {...}
      });`

**Comment by tylerkelly13** [comment]
Hi @ShivSoni5 ,

There are two issues.
- The bomb icon is appearing due to a bug in TinyMCE. This bug is fixed in TinyMCE 5.4, which will be released to the community later today. The initial bug report can be found here: https://github.com/tinymce/tinymce/issues/5059
- The svg string you have provided is incomplete. You need to provide the <svg> element, not just the path. I've created a 'demo' with your svg path here: http://fiddle.tinymce.com/Tmhaab

I'll create a fix for the API docs to be more specific, hopefully today.

Hope this helps!
Tyler

**Comment by tylerkelly13** [comment]
The updated API docs for `addIcon` is now live: https://www.tiny.cloud/docs/api/tinymce.editor.ui/tinymce.editor.ui.registry/#addicon

Thanks again for letting us know about this issue.
