### ISSUE TITLE
unable to use "import" statement

### ISSUE THREAD

**Issue by abhijeetj100** [tinymce/tinymce-docs#1606]
I was trying to import tinymce using: 

`import * from tinymce from 'tinymce/tinymce';
`
But this does not work.

But this:

`const tinymce  = require('tinymce/tinymce')`

works.

Is there a way I could use import instead of require ?

**Comment by lnewson** [comment]
Hi @abhijeetj100, you can find that information here: https://www.tiny.cloud/docs/advanced/usage-with-module-loaders/#es2015modules

TinyMCE only includes a default export, not a named export so you should be able to get it working by changing that to
```
import tinymce from 'tinymce/tinymce';
```

**Comment by abhijeetj100** [comment]
@lnewson 
I am trying to import this is a typescript file. I had tried what you suggested too but didn't work.

Later I used `npm install @types/tinymce`, that worked for me.

**Comment by lnewson** [comment]
Ahh, you didn't mention you were using TypeScript. Yes, you'll need something like that for TypeScript, I will note however those types aren't maintained by, they were created by the community as part of the DefinitelyTyped project for TinyMCE 4.5.x.  We currently don't publish types ourself, but we're trying to find a solution for that (see https://github.com/tinymce/tinymce/issues/3427).

Anyways, since you've managed to get this working, I'll go ahead and close this.

**Comment by abhijeetj100** [comment]
yeah, my bad 😜 @lnewson
