### ISSUE TITLE
Any thing for User Spice 5?

### ISSUE THREAD

**Issue by PaulMcDowell-sp** [tinymce/tinymce-docs#1830]
I use php and user spice 5 for development. Which do you suggest for the platform in the account setup?

**Comment by tylerkelly13** [comment]
Hi @PaulMcDowell-sp ,

If you are referring to the "platform/framework" options presented when signing up for a Tiny Cloud API Key, the option is no important, it just determines which "quick-start" is shown during the set-up process.

If this answers your question, or you have already resolved the issue, let me know. Otherwise, can you provide more details?

Tyler

**Comment by PaulMcDowell-sp** [comment]
Thank you. I was able to install it :)

**Comment by tylerkelly13** [comment]
Awesome, thanks for letting us know. :)
