### ISSUE TITLE
Hierarchical formats with custom formats

### ISSUE THREAD

**Issue by jbriner-pearson** [tinymce/tinymce-docs#1915]
**Documentation/Product Version**
 _TinyMCE 5 Documentation_

**Related page URL (if applicable)**

**I would like to know...**
If the default "formats" are used, a hierarchical menu is created with "Headings", "Inline", "Blocks", "Align". I would like to add my custom formats with a heading of "Mine", e.g. If I cannot do that, is there a way to keep the others in the existing hierarchy?

**Comment by tylerkelly13** [comment]
Hi @jbriner-pearson,

To add custom formats, you can use the `style_formats` option: https://www.tiny.cloud/docs/configure/editor-appearance/#style_formats
If you want to append your menu, rather than replace the existing formats, include the default formats provided on the above page.
For an example of what I think you are trying to do, please look at the second interactive example here: https://www.tiny.cloud/docs/configure/editor-appearance/#interactiveexamples

Let me know if this helps.

Tyler

**Comment by tylerkelly13** [comment]
This issue seems to have been resolved and will now be closed.
Please create a new issue if this issue should not have been closed.
