### ISSUE TITLE
Problem with page plugins/colorpicker.md

### ISSUE THREAD

**Issue by otherblandart** [tinymce/tinymce-docs#1997]
This page shows a _color_picker_callback_ option for including our own custom color picker, but it's not very useful without a more detailed example of how to implement one. I haven't been able to find an example on stackoverflow either :(

> *affected page: https://www.tiny.cloud/docs-4x/plugins/colorpicker/*

**Comment by tylerkelly13** [comment]
Hi @otherblandart ,

Unfortunately TinyMCE 4.x is no longer supported (see https://www.tiny.cloud/blog/tinymce-4-support-window/). TinyMCE 5 is our supported community version. I'm going to close this issue since it's not a version we are supporting.

However, here is the default behavior of the `color_picker_callback` option, which should help:
https://github.com/tinymce/tinymce/blob/4.9.11/src/plugins/colorpicker/main/ts/Plugin.ts

Tyler
