### ISSUE TITLE
image insert

### ISSUE THREAD

**Issue by phiskal** [tinymce/tinymce-docs#2079]
I would like to use this for a textarea field on a web page
I'm looking for the option to insert an image or video where the button will bring up an option to click on an image or video on your drive and insert into the edit. The image or video can then be saved on the server.

**Comment by tylerkelly13** [comment]
Hi @phiskal ,

To enable image and media handling, add the `image` and `media` plugins. See the docs for information on adding the toolbar buttons and/or menu items:
- https://www.tiny.cloud/docs/plugins/opensource/image/
- https://www.tiny.cloud/docs/plugins/opensource/media/
You'll also need to configure the `file_picker_callback` option so that users can upload local files:
https://www.tiny.cloud/docs/plugins/opensource/image/#file_picker_callback

Tyler

**Comment by tylerkelly13** [comment]
This issue seems to have been resolved.
Please reopen or create a new issue if this issue should not have been closed.
