### ISSUE TITLE
I can't find what I'm looking for: plugins/opensource/print.md

### ISSUE THREAD

**Issue by Songxna** [tinymce/tinymce-docs#2161]
How to set pagination and header footer when printing?No specific instructions.

**Comment by tylerkelly13** [comment]
Hi @Songxna ,

The "Page break" option (provided by the `pagebreak` plugin) provides a way to manually define page breaks:
![image](https://user-images.githubusercontent.com/14833627/140450876-0e2973f6-005f-4631-ab14-a4bb02040974.png)
otherwise; pagination, headers, and footers can only be set in the "Print" dialog, which is part of the web browser and/or your Operating System (Windows, macOS, etc) so it varies between browsers and devices.

Tyler

**Comment by tylerkelly13** [comment]
This issue seems to have been resolved.
Please create a new issue if this issue should not have been closed.
