### ISSUE TITLE
I can't find what I'm looking for: configure/localization.md

### ISSUE THREAD

**Issue by shaheryar3640** [tinymce/tinymce-docs#2181]
how to set mltiple language and also image in tinymce? plzz help

**Comment by tylerkelly13** [comment]
Hi @shaheryar3640 ,

Looks like you were on the wrong page for localization. Try https://www.tiny.cloud/docs/general-configuration-guide/localize-your-language/
Regarding "image":
- to allow images, add the image plugin: https://www.tiny.cloud/docs/plugins/opensource/image/
- to upload images to a file on your server (instead of converting them to base64 blobs), see: https://www.tiny.cloud/docs/general-configuration-guide/upload-images/

Tyler

**Comment by tylerkelly13** [comment]
This issue seems to have been resolved.
Please create a new issue if this issue should not have been closed.
