### ISSUE TITLE
Problem with page plugins/codesample.md

### ISSUE THREAD

**Issue by kilianc** [tinymce/tinymce-docs#227]
### [Codesample Plugin](/tinymce/tinymce-docs/blob/master/plugins/codesample.md) issue:

The page doesn't explain that you need to include the prismjs css in the `content_css` array.

We should provide a list of themes in the cdn as well.

**Comment by r12s** [comment]
i couldn't replicate this. the prismjs syntax highlighting appeared in snippets when using the cdn and also in a test with tinymce installed locally, both without including `content_css`.

that said, the description of the plugin using `prismjs.com` is confusing and i will update the content.

**Comment by kilianc** [comment]
I can't test anymore because the snippet is gone from http://codepen.io/tinymce/pen/Madpwx

**Comment by r12s** [comment]
@kilianc issue was that the snippet in the codepen became a noneditable object. the intent of providing a snippet was to make it easy for a user to cut/paste the content into the codesample dialog. since it didn't serve that function i removed it. i need to create a simple local test instance to see what happens when a codesample snippet is posted.

keeping this open as the description is still accurate :-) assigning to me.
