### ISSUE TITLE
Problem with page plugins/media.md

### ISSUE THREAD

**Issue by pramach** [tinymce/tinymce-docs#270]
> *affected page: https://www.tinymce.com/docs/plugins/media/*

Version: // 4.2.8 (2015-11-13)
In media/plugin.min.js there is a limitation somehow to width & height to 300 px.
When I set in dimension field "width" a size greater than 300, it reduces to 300.
However, regardless which height I enter, it stays.

Is there any reason why this maximum width of 300px exists ?

Btw also checked in 4.3.1. and there seems same limitation .....

**Comment by r12s** [comment]
Thanks @pramach this sounds like either a bug or possibly an intended editor behavior, rather than a problem with the documentation.

Please raise an issue in the tinymce repo https://github.com/tinymce/tinymce/issues or ask a question on the TinyMCE Community forum. http://community.tinymce.com/forum/

Thanks again, I appreciate you taking the time to raise the issue. Marking closed.
