### ISSUE TITLE
Problem with page advanced/handle-async-image-uploads.md

### ISSUE THREAD

**Issue by huaraco** [tinymce/tinymce-docs#284]
I cannot find where can i trigger the upload image function

> _affected page: https://www.tinymce.com/docs/advanced/handle-async-image-uploads/_

**Comment by DanH42** [comment]
Since it's been a few months and this hasn't been addressed, I'll expand on the problem description:

I just ran into the same trouble. After reading through the File & Image Upload page, I still can't figure out how I'm supposed to make File & Image Uploads work. Using the latest TinyMCE version, one of the sample code on that page results in an upload button that brings up a file selection dialog when clicked. After researching elsewhere, everyone else who's doing this is either using a third party plugin or writing their own custom upload logic themselves. This help page references "TinyMCE's default JavaScript upload handler function" but never clarifies how to invoke this upload handler. The "Handle Async Image Uploads" page refers to some of the same arguments as the last help page, but still doesn't provide any working examples. It seems to assume you already have a working non-asynchronous upload handler in place. Even the "Rolling your own image handler" example still doesn't result in an editor that gives the user an option to upload an image.

I'm still confused what this page is even referencing.

**Comment by tylerkelly13** [comment]
> "TinyMCE's default JavaScript upload handler function"

Refers to the [uploadImages API method](https://www.tiny.cloud/docs/api/tinymce/tinymce.editor/#uploadimages).
The following pages have been updated:
https://www.tiny.cloud/docs/advanced/handle-async-image-uploads/
https://www.tiny.cloud/docs/general-configuration-guide/upload-images/
