### ISSUE TITLE
I can't find what I'm looking for: plugins/premium/advcode.md

### ISSUE THREAD

**Issue by sirtet** [tinymce/tinymce-docs#2859]
Does that plugin not have the ability to synchronize cursor position and text highlighting when switching between code and wysiwyg?

**Comment by brian-forte** [comment]
> Does that plugin not have the ability to synchronize cursor position
> and text highlighting when switching between code and wysiwyg?

The short answer is that, when using either the [Advanced Code Editor](https://tiny.cloud/docs/tinymce/6/advcode/) Premium plugin, or the open source [Code](https://tiny.cloud/docs/tinymce/6/code/) plugin, it is safest to assume selection state is *not* preserved.

The longer answer is that both plugins take some pains to preserve selection state when switching from the rich-text editor to the code editor dialog.

If the current selection in the rich-text editor is collapsed (ie, is a flashing insertion point), the insertion point will be in the equivalent place when the code view dialog opens.

If the current selection in the rich-text editor is an actual selection, that state is not preserved when switching to the code view dialog, but the insertion point in the code-view dialog is placed at the beginning of what was the selection in the rich-text editor.

However, when switching back from the code-view dialog to the rich-text editor, selection state is almost never preserved.

If you have a selection or a collapsed selection in the rich-text editor and

1. open the code view dialog;
2. make no changes; and
3. exit the code view dialog by clicking **Cancel** (or pressing the **Esc** key)

the selection or collapsed selection will likely be preserved in the rich-text editor.

Otherwise, the selection state is not preserved on round-tripping from rich-text to code-view and back.

I had a discussion with the responsible engineers and, while they agreed it would be a useful behaviour, they noted that, because of the opaqueness of the data serialisation when switching between these two views, this is more difficult and complex a problem to solve safely than might be expected.

I cannot predict what features will be added to TinyMCE or any of its plugins. I will note, however, there are currently no plans to add this particular feature to either of these plugins.
