### ISSUE TITLE
Suggestion: Please consider adding more detail about class properties and methods to docs

### ISSUE THREAD

**Issue by dsifford** [tinymce/tinymce-docs#317]
I'd like to see a list of properties for various plugin field types. Additionally, I'd like to see the listed methods also list the parameters that it accepts.

**Edit 05/02/2016:** Venting frustrations and listing problems, rather than solutions is not productive. Fixed.

**Comment by dsifford** [comment]
Yep, still looking for available methods and finding nothing..

Nowhere in the docs does it talk about how to resize a windowmanager instance. I've resorted to this because if I have to read one more word of your documentation, I just might lose my mind.

```ts
let modalContainer = top.document.querySelector('div.mce-floatpanel[aria-label="Insert Formatted Reference"]');
  (<any>modalContainer).style.height = '100%';
  (<any>modalContainer).children[0].children[1].style.height = '100%';
```

Seriously embarrassingly bad.

**Comment by blunckr** [comment]
I'm also having trouble with it. the docs for `init()` says this:
"Initializes a set of editors. This method will create editors based on various settings."
What are the settings? We need a list of options.

**Comment by spocke** [comment]
The windowManager.open call needs to reference a whole documentation section since it can contain any of the UI options available and that is a complex json structure. So adding that to the API docs wouldn't be feasible. Will discuss this internally how we can improve the docs on this.

@blunckr The init settings are the all the settings for tinymce found here:
https://www.tinymce.com/docs/configure/ so the same goes here it needs to link to that rather than having every available option there.

**Comment by benvh** [comment]
@spocke how about adding a list of possible properties for each UI component on their respective pages? That would be a nice start! Every UI component's type name would also be nice, because these aren't documented either...

Delving into the tinyMCE sources because of a lack of documentation, now **THAT** is most unfeasible...

**Comment by androb** [comment]
cc @r12s and @MichaelFromin to look at what we can do.

**Comment by tylerkelly13** [comment]
The properties for each UI component can be found in the UI components section: https://www.tiny.cloud/docs/ui-components/
