### ISSUE TITLE
Problem with page demo/full-featured.md

### ISSUE THREAD

**Issue by SkyBooj** [tinymce/tinymce-docs#318]
The code that's producing the example isn't copy-pasteable so that it'll work in my application. I haven't read the full docs yet and that may mean that I'm missing a script higher up or something like that, but I think that if you make the code available as you have through CodePen, it would be better if it worked right after copying and pasting.

> *affected page: https://www.tinymce.com/docs/demo/full-featured/*

**Comment by r12s** [comment]
@SkyBooj the purpose of the demo is to highlight certain functionality. Codepen works in such a way that we include the script elsewhere in the setup rather than in the JS code snippet, so we can't do what you're asking (even if we wanted to).

This page discusses how to instantiate the editor:
https://www.tinymce.com/docs/get-started/first-steps/

The full Get Started guide can be found here:
https://www.tinymce.com/docs/get-started/
