### ISSUE TITLE
Problem with page get-started/first-steps.md

### ISSUE THREAD

**Issue by RMIGHTY1** [tinymce/tinymce-docs#371]
I do not know all that code stuff or where to put it. I am a simple WordPress user and want to specify fonts, sizes and colors via my wysiwyg editor. Where do I learn how to do that? The various aditoe plugins like WP-Edit seem to show that in their config but it does not show up in the actual editor. I cannot fix my type the way I like it. How do I do so? Whre do I go to make it work for me?

> *affected page: https://www.tinymce.com/docs/get-started/first-steps/*

**Comment by jayarjo** [comment]
WordPress has a great plugin (similar to WP-Edit?) by Andrew Ozz - [TinyMCE Advanced](https://wordpress.org/plugins/tinymce-advanced/). Give it a try maybe.

Otherwise it doesn't seem to be TinyMCE issue. I'm afraid you will have to ask it on WordPress FAQ sites like [Wordpress Development](http://wordpress.stackexchange.com/) for example.
