### ISSUE TITLE
Duplicate entry

### ISSUE THREAD

**Issue by tim-thatcher** [tinymce/tinymce-docs#41]
Configuration Settings -> Editor Appearance: There are two entries for 'toolbar', the second of which is broken.

**Comment by r12s** [comment]
@kilianc the situation here is that there are in fact two config options "toolbar" (file: toolbar.md) and "toolbar<N>" (file: toolbar-n.md). toolbar<N> meta title is "toolbar&lt;N&gt;".

My recollection is that I wrote the title like that because `<` and `>` characters are stripped from the title when rendered, along with the N character.

Whatever the case the end result is a broken link.

**Comment by kilianc** [comment]
why do we have an option called `"toolbar<N>"` is the real question :D I am trying to figure out a solution
