### ISSUE TITLE
4.5.0 breaks my bullet list and numlist on toolbar

### ISSUE THREAD

**Issue by away86** [tinymce/tinymce-docs#438]
4.5.0 broke my bullet list and numlist on toolbar (those two disappeared). I then had to go back to 4.4.3 to make it work.

**Comment by fyrkant** [comment]
Hi! This is the respository for the TinyMCE documentation, if you have a problem with TinyMCE in itself [open an issue on the correct repository](https://github.com/tinymce/tinymce/issues). 

So please copy this issue over there, and maybe try to recreate your problem in a [fiddle](http://fiddle.tinymce.com/) so it's easier for us to find what the problem is.
