### ISSUE TITLE
Problem with page advanced/creating-a-skin.md

### ISSUE THREAD

**Issue by orporan** [tinymce/tinymce-docs#505]
how to I load the created skin?

> *affected page: https://www.tinymce.com/docs/advanced/creating-a-skin/*

**Comment by fyrkant** [comment]
You should be able to specify the url to the skin with the `skin_url` setting: https://www.tinymce.com/docs/configure/editor-appearance/#skin_url

**Comment by cjdubois10** [comment]
Hi @orporan do you think that this is actually a documentation issue that needs to be fixed in the docs? or can this issue be closed because it was a specific question that seems to have been answered? If so closing this issue should be considered. Also, if you have other issues that are more specific questions pertaining to your application of TinyMCE, you might find the TinyMCE community helpful: [](https://community.tinymce.com/)

**Comment by cjdubois10** [comment]
Hi @orporan do you think that this is actually a documentation issue that needs to be fixed in the docs? or can this issue be closed because it was a specific question that seems to have been answered? If so closing this issue should be considered. Also, if you have other issues that are more specific questions pertaining to your application of TinyMCE, you might find the TinyMCE community helpful:
https://community.tinymce.com/

**Comment by tylerkelly13** [comment]
This issue has been resolved.
Please reopen or create a new issue if this issue should not have been closed.
