### ISSUE TITLE
Content/pages from old site missing in redesign

### ISSUE THREAD

**Issue by r12s** [tinymce/tinymce-docs#52]
There are links in the docs pointing to pages on the "old" site that (as far as I know) haven't been discussed in the redesign and therefore don't yet exist.

* http://www.tinymce.com/i18n/index.php
* http://www.tinymce.com/download/compressors.php
* http://www.tinymce.com/develop/develop.php

Are there any others?

**Comment by lucaorio** [comment]
@r12s 
* **languages** is already designed and merged to the download page (it's not part part of the upcoming release, we need to link to the old website) https://invis.io/FE4GS6ZZH
* I already discussed with Andrew about the **develop** pages and we decided to drop them because their content is already re-proposed across the website in a different way
* my understanding was that the compressors were not used anymore? Not 100% sure about this one, please correct me if I'm wrong.
