### ISSUE TITLE
Problem with page advanced/creating-a-custom-button.md

### ISSUE THREAD

**Issue by rob-gordon** [tinymce/tinymce-docs#564]
> *affected page: https://www.tinymce.com/docs/advanced/creating-a-custom-button/*

I was really happy to find this example because I had been scouring the internet for a toggle button example. The only problem with this example is that it doesn't show how you would connect it to a custom command. I searched through the source for where the command `strikethrough` is registered so that I could mimmic the functionality, but I wasn't able to find it. Maybe you could add a custom command to the example, or possibly point me to where toggle commands like bold, italics, strikethrough, etc. are registered in the source.

Thanks!

**Comment by jayarjo** [comment]
Since striking the text out is basically a form of the formatting, we preferred generic `mceToggleFormat` command to creating new one, that would basically do the same thing. If you are looking to add your own custom command, check the API docs for [editor.addCmmmand()](https://www.tinymce.com/docs/api/tinymce/tinymce.editor/#addcommand) method. But then inside it will still be simpler to invoke generic `mceToggleFormat` command.
