### ISSUE TITLE
Add article on configuring for multiple editors on single page

### ISSUE THREAD

**Issue by tim-thatcher** [tinymce/tinymce-docs#67]
A pretty common use case is for people to want to have multiple editable spots on a single page.  This can be done in both classic mode (not as often) as well as inline (very common).  This topic doesn't appear to be addressed anywhere else in the documentation and we do get questions on this that come into support.  I recommend we document the following:
* How and why to use multiple inits (ex. I want to have different config for editing H1s vs. Divs)
* How to use sector within single TinyMCE init. There are multiple ways of doing this.  We don't need to describe all of them, but a couple of examples would be good.  
* examples for inline and maybe one for classic.

**Comment by r12s** [comment]
Agree @tim-thatcher sounds like slightly complex content and if it's quite common we should go into some detail. Who on the product team can kick it off? I'm very happy to work with them on it.

**Comment by tim-thatcher** [comment]
@r12s I created a draft of this document and did a pull request.  I created as though it would go into the getting started section, but it could also go into the Other Topics section.  Let me know what you think.

**Comment by r12s** [comment]
@tim-thatcher great article. i thought about whether it should go in advanced topics or perhaps even as an example, but it fills a hole in the get started guide, shows the ease and flexibility of Tiny. I'll update the article with links to the inline examples page.

I placed it after the inline page since we need to introduce that functionality first.
http://beta.tinymce.com/docs/get-started/multiple-editors/
